// resources/js/components/seo/Seo.vue
<script setup lang="ts">
import { Head } from "@inertiajs/vue3";
import { computed } from "vue";
import type { SeoData } from "@/types";

const props = defineProps<{ seo: SeoData }>();

const twitterCard = computed(() => (props.seo.ogImage ? "summary_large_image" : "summary"));
</script>

<template>
    <Head :title="seo.title">
        <meta v-if="seo.description" name="description" :content="seo.description" />
        <meta v-if="seo.noindex" name="robots" content="noindex, nofollow" />
        <link v-if="seo.canonical" rel="canonical" :href="seo.canonical" />

        <link
            v-for="alternate in seo.alternates"
            :key="alternate.locale"
            rel="alternate"
            :hreflang="alternate.locale"
            :href="alternate.url"
        />

        <meta property="og:title" :content="seo.title" />
        <meta v-if="seo.description" property="og:description" :content="seo.description" />
        <meta property="og:type" :content="seo.ogType" />
        <meta v-if="seo.canonical" property="og:url" :content="seo.canonical" />
        <meta v-if="seo.ogImage" property="og:image" :content="seo.ogImage" />

        <meta name="twitter:card" :content="twitterCard" />
        <meta name="twitter:title" :content="seo.title" />
        <meta v-if="seo.description" name="twitter:description" :content="seo.description" />
        <meta v-if="seo.ogImage" name="twitter:image" :content="seo.ogImage" />

        <component :is="'script'" v-for="(schema, index) in seo.jsonLd" :key="index" type="application/ld+json">{{
            JSON.stringify(schema)
        }}</component>
    </Head>
</template>

// resources/js/components/seo/Seo.tsx
import { Head } from "@inertiajs/react";
import type { SeoData } from "@/types";

export function Seo({ seo }: { seo: SeoData }) {
  const twitterCard = seo.ogImage ? "summary_large_image" : "summary";

  return (
    <Head title={seo.title}>
      {seo.description && <meta name="description" content={seo.description} />}
      {seo.noindex && <meta name="robots" content="noindex, nofollow" />}
      {seo.canonical && <link rel="canonical" href={seo.canonical} />}

      {seo.alternates.map((alternate) => (
        <link
          key={alternate.locale}
          rel="alternate"
          hrefLang={alternate.locale}
          href={alternate.url}
        />
      ))}

      <meta property="og:title" content={seo.title} />
      {seo.description && (
        <meta property="og:description" content={seo.description} />
      )}
      <meta property="og:type" content={seo.ogType} />
      {seo.canonical && <meta property="og:url" content={seo.canonical} />}
      {seo.ogImage && <meta property="og:image" content={seo.ogImage} />}

      <meta name="twitter:card" content={twitterCard} />
      <meta name="twitter:title" content={seo.title} />
      {seo.description && (
        <meta name="twitter:description" content={seo.description} />
      )}
      {seo.ogImage && <meta name="twitter:image" content={seo.ogImage} />}

      {seo.jsonLd.map((schema, index) => (
        <script key={index} type="application/ld+json">
          {JSON.stringify(schema)}
        </script>
      ))}
    </Head>
  );
}
