// resources/js/components/content/Breadcrumbs.vue
<script setup lang="ts">
import { Link } from "@inertiajs/vue3";
import { ChevronRight } from "@lucide/vue";
import type { Breadcrumb } from "@/types";

defineProps<{ items: Breadcrumb[] }>();
</script>

<template>
    <nav aria-label="Breadcrumb" class="mx-auto max-w-6xl px-4 py-4 sm:px-6 lg:px-8">
        <ol class="text-muted-foreground flex flex-wrap items-center gap-1.5 text-sm">
            <li v-for="(item, index) in items" :key="index" class="flex items-center gap-1.5">
                <Link
                    v-if="item.url"
                    :href="item.url"
                    class="hover:text-foreground transition-colors"
                >
                    {{ item.label }}
                </Link>
                <span v-else class="text-foreground font-medium">{{ item.label }}</span>
                <ChevronRight v-if="index < items.length - 1" class="size-3.5 shrink-0" />
            </li>
        </ol>
    </nav>
</template>

// resources/js/components/content/Breadcrumbs.tsx
import { Link } from "@inertiajs/react";
import { ChevronRight } from "lucide-react";
import { Fragment } from "react";
import { useT } from "@/hooks/use-t";
import type { Breadcrumb } from "@/types";

export function Breadcrumbs({ items }: { items: Breadcrumb[] }) {
  const t = useT();

  return (
    <nav aria-label={t("common.breadcrumb")}>
      <ol className="text-muted-foreground flex flex-wrap items-center gap-x-1.5 gap-y-1 text-sm">
        {items.map((item, index) => (
          <Fragment key={index}>
            <li>
              {item.url ? (
                <Link
                  href={item.url}
                  className="hover:text-primary underline-offset-4 hover:underline"
                >
                  {item.label}
                </Link>
              ) : (
                <span
                  aria-current="page"
                  className="text-foreground font-semibold"
                >
                  {item.label}
                </span>
              )}
            </li>
            {index < items.length - 1 && (
              <li aria-hidden="true" className="flex">
                <ChevronRight className="size-3.5" />
              </li>
            )}
          </Fragment>
        ))}
      </ol>
    </nav>
  );
}
