// resources/js/components/layout/AppHeader.tsx
import { Link, usePage } from "@inertiajs/react";
import { Mail, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useActiveLink } from "@/hooks/use-active-link";
import { useNavUrl } from "@/hooks/use-nav-url";
import { useT } from "@/hooks/use-t";
import { cn, telHref } from "@/lib/utils";
import { Container } from "./Container";
import { LanguageSwitch } from "./LanguageSwitch";
import { Logo } from "./Logo";
import { MobileNav } from "./MobileNav";

export function AppHeader() {
  const t = useT();
  const { navigation, site } = usePage().props;
  const getCurrent = useActiveLink();
  const contactUrl = useNavUrl("nav.contact", "/contact");

  return (
    <>
      <div className="surface-navy bg-navy text-navy-foreground hidden lg:block">
        <Container className="flex h-10 items-center justify-between text-sm">
          <div className="flex items-center gap-6">
            <a
              href={telHref(site.contact.phone)}
              className="text-navy-muted flex items-center gap-2 font-medium hover:text-white"
            >
              <Phone className="text-accent size-3.5" aria-hidden="true" />
              {site.contact.phone}
            </a>
            <a
              href={`mailto:${site.contact.email}`}
              className="text-navy-muted flex items-center gap-2 font-medium hover:text-white"
            >
              <Mail className="text-accent size-3.5" aria-hidden="true" />
              {site.contact.email}
            </a>
          </div>
          <LanguageSwitch />
        </Container>
      </div>

      <header className="bg-background/95 supports-backdrop-filter:bg-background/85 sticky top-0 z-40 w-full border-b backdrop-blur">
        <Container className="text-primary flex h-16 items-center justify-between gap-6 lg:h-20">
          <Logo />

          <nav
            aria-label={t("common.mainNavigation")}
            className="hidden items-center gap-8 lg:flex"
          >
            {navigation.map((link) => {
              const current = getCurrent(link);

              return (
                <Link
                  key={link.url}
                  href={link.url}
                  aria-current={current}
                  className={cn(
                    "relative py-2 text-sm font-semibold transition-colors",
                    current
                      ? "text-primary"
                      : "text-muted-foreground hover:text-primary",
                  )}
                >
                  {t(link.labelKey)}
                  {current && (
                    <span
                      className="bg-accent absolute inset-x-0 -bottom-px h-0.5 rounded-full"
                      aria-hidden="true"
                    />
                  )}
                </Link>
              );
            })}
          </nav>

          <div className="flex items-center gap-2">
            <Button asChild variant="accent" className="hidden sm:inline-flex">
              <Link href={contactUrl}>{t("common.requestQuote")}</Link>
            </Button>
            <MobileNav />
          </div>
        </Container>
      </header>
    </>
  );
}

// resources/js/components/layout/AppHeader.vue
<script setup lang="ts">
import { Link, usePage } from "@inertiajs/vue3";
import { useScroll } from "@vueuse/core";
import { Languages, Menu } from "@lucide/vue";
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import { Button } from "@/components/ui/button";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useActiveLink } from "@/composables/useActiveLink";
import { useLocale } from "@/composables/useLocale";
import type { SharedData } from "@/types";
import MobileNav from "./MobileNav.vue";

const { t } = useI18n();
const page = usePage<SharedData>();
const { current, available } = useLocale();
const { isActive } = useActiveLink();
const mobileNavOpen = ref(false);

const homeUrl = computed(
    () => page.props.navigation.find((link) => link.labelKey === "nav.home")?.url ?? "/",
);

const { y: scrollY } = useScroll(window);
const isScrolled = computed(() => scrollY.value > 8);
</script>

<template>
    <header
        class="bg-background/80 supports-backdrop-filter:bg-background/60 sticky top-0 z-40 w-full border-b backdrop-blur transition-shadow duration-200"
        :class="isScrolled ? 'border-border/60 shadow-sm' : 'border-transparent'"
    >
        <div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6 lg:px-8">
            <Link
                :href="homeUrl"
                class="font-heading hover:text-primary text-xl font-semibold tracking-tight transition-colors"
            >
                AmpSquad
            </Link>

            <nav class="hidden items-center gap-8 md:flex">
                <Link
                    v-for="link in page.props.navigation"
                    :key="link.url"
                    :href="link.url"
                    :aria-current="isActive(link.url) ? 'page' : undefined"
                    class="relative py-1 text-sm font-medium transition-colors"
                    :class="isActive(link.url) ? 'text-foreground' : 'text-muted-foreground hover:text-foreground'"
                >
                    {{ t(link.labelKey) }}
                    <span
                        v-if="isActive(link.url)"
                        class="bg-primary absolute -bottom-1 left-0 h-0.5 w-full rounded-full"
                        aria-hidden="true"
                    />
                </Link>
            </nav>

            <div class="flex items-center gap-2">
                <DropdownMenu>
                    <DropdownMenuTrigger as-child>
                        <Button variant="ghost" size="icon" :aria-label="t('common.switchLanguage')">
                            <Languages class="size-4" />
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                        <DropdownMenuItem v-for="locale in available" :key="locale.code" as-child>
                            <Link
                                :href="locale.url"
                                :class="[
                                    'w-full',
                                    locale.code === current ? 'text-primary font-semibold' : '',
                                ]"
                            >
                                {{ locale.name }}
                            </Link>
                        </DropdownMenuItem>
                    </DropdownMenuContent>
                </DropdownMenu>

                <Button
                    variant="ghost"
                    size="icon"
                    class="md:hidden"
                    :aria-label="t('common.openMenu')"
                    @click="mobileNavOpen = true"
                >
                    <Menu class="size-5" />
                </Button>
            </div>
        </div>

        <MobileNav v-model:open="mobileNavOpen" />
    </header>
</template>
