// resources/js/Pages/Error.tsx
import { Link } from "@inertiajs/react";
import { Container } from "@/components/layout/Container";
import { Button } from "@/components/ui/button";
import { useNavUrl } from "@/hooks/use-nav-url";
import { useT } from "@/hooks/use-t";

export default function Error({ status }: { status: 403 | 404 | 500 | 503 }) {
  const t = useT();
  const homeUrl = useNavUrl("nav.home", "/");
  const key = `${status}` as const;

  return (
    <section className="bg-surface">
      <Container size="narrow" className="py-24 sm:py-32">
        <span
          className="bg-accent mb-6 block h-1 w-14 rounded-full"
          aria-hidden="true"
        />
        <h1 className="text-primary text-4xl sm:text-5xl">
          {t(`errors.${key}.title`)}
        </h1>
        <p className="text-muted-foreground mt-5 max-w-xl text-lg">
          {t(`errors.${key}.description`)}
        </p>
        <Button asChild variant="accent" size="lg" className="mt-8">
          <Link href={homeUrl}>{t("errors.backHome")}</Link>
        </Button>
      </Container>
    </section>
  );
}

// resources/js/Pages/Error.vue
<script setup lang="ts">
import { Link } from "@inertiajs/vue3";
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import Seo from "@/components/seo/Seo.vue";
import { Button } from "@/components/ui/button";
import AppLayout from "@/layouts/AppLayout.vue";
import type { SeoData } from "@/types";

const props = defineProps<{ status: 403 | 404 | 500 | 503; seo: SeoData }>();

const { t } = useI18n();

const key = computed(() => String(props.status) as "403" | "404" | "500" | "503");
</script>

<template>
    <Seo :seo="seo" />

    <AppLayout>
        <section class="mx-auto flex max-w-2xl flex-col items-start gap-6 px-4 py-32 text-center sm:items-center sm:px-6 lg:px-8">
            <h1 class="font-heading text-4xl font-semibold tracking-tight sm:text-5xl">
                {{ t(`errors.${key}.title`) }}
            </h1>
            <p class="text-muted-foreground text-lg">
                {{ t(`errors.${key}.description`) }}
            </p>
            <Button as-child>
                <Link href="/">{{ t("errors.backHome") }}</Link>
            </Button>
        </section>
    </AppLayout>
</template>
