// resources/js/components/home/CalculatorTeaserSection.vue
<script setup lang="ts">
import { Link } from "@inertiajs/vue3";
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import Reveal from "@/components/common/Reveal.vue";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { resolveHeroicon } from "@/lib/heroicon";
import type { CalculatorCategoryTeaser } from "@/types";

const props = defineProps<{ categories: CalculatorCategoryTeaser[]; contactUrl: string }>();

const { t } = useI18n();

const categoryIcons = computed(() =>
    Object.fromEntries(props.categories.map((category) => [category.id, resolveHeroicon(category.icon)])),
);
</script>

<template>
    <section v-if="categories.length" class="bg-section-wash py-20">
        <div class="mx-auto max-w-6xl px-4 text-center sm:px-6 lg:px-8">
            <Reveal>
                <h2 class="font-heading text-3xl font-semibold tracking-tight sm:text-4xl">
                    {{ t("home.calculator.title") }}
                </h2>
                <p class="text-muted-foreground mx-auto mt-4 max-w-xl text-lg text-pretty">
                    {{ t("home.calculator.subtitle") }}
                </p>
            </Reveal>

            <div class="mt-10 grid gap-6 sm:grid-cols-3">
                <Reveal v-for="(category, index) in categories" :key="category.id" :delay="index * 75">
                    <Card
                        class="hover:shadow-warm-lg h-full p-6 text-left transition-all duration-300 hover:-translate-y-1"
                    >
                        <span
                            v-if="categoryIcons[category.id]"
                            class="bg-primary/10 text-primary mb-3 inline-flex size-11 items-center justify-center rounded-full"
                        >
                            <component :is="categoryIcons[category.id]" class="size-5" />
                        </span>
                        <h3 class="font-heading text-lg font-semibold">{{ category.name }}</h3>
                        <ul v-if="category.options.length" class="text-muted-foreground mt-3 space-y-1 text-sm">
                            <li v-for="option in category.options" :key="option">{{ option }}</li>
                        </ul>
                    </Card>
                </Reveal>
            </div>

            <Button as-child size="lg" class="hover:shadow-warm-md mt-10 transition-all duration-200 hover:scale-[1.02]">
                <Link :href="contactUrl">{{ t("home.calculator.cta") }}</Link>
            </Button>
        </div>
    </section>
</template>

// resources/js/components/home/CalculatorTeaserSection.tsx
import { Link } from "@inertiajs/react";
import { Check } from "lucide-react";
import { Reveal } from "@/components/common/Reveal";
import { SectionHeading } from "@/components/common/SectionHeading";
import { Container } from "@/components/layout/Container";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useT } from "@/hooks/use-t";
import { HeroIcon } from "@/lib/heroicon";
import type { CalculatorCategoryTeaser } from "@/types";

interface CalculatorTeaserSectionProps {
  categories: CalculatorCategoryTeaser[];
  contactUrl: string;
}

export function CalculatorTeaserSection({
  categories,
  contactUrl,
}: CalculatorTeaserSectionProps) {
  const t = useT();

  if (categories.length === 0) {
    return null;
  }

  return (
    <section className="bg-surface py-16 sm:py-24">
      <Container>
        <Reveal>
          <SectionHeading
            title={t("home.calculator.title")}
            description={t("home.calculator.subtitle")}
            action={
              <Button
                asChild
                variant="accent"
                size="lg"
                className="self-start sm:self-auto"
              >
                <Link href={contactUrl}>{t("home.calculator.cta")}</Link>
              </Button>
            }
          />
        </Reveal>

        <ul className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {categories.map((category, index) => (
            <li key={category.id}>
              <Reveal delay={index * 75} className="h-full">
                <Card className="hover:shadow-card-hover h-full border-t-4 border-t-accent p-6 transition-shadow duration-300">
                  <span className="bg-secondary text-primary mb-4 inline-flex size-12 items-center justify-center rounded-lg">
                    <HeroIcon name={category.icon} className="size-6" />
                  </span>
                  <h3 className="text-primary text-xl">{category.name}</h3>
                  {category.options.length > 0 && (
                    <ul className="text-muted-foreground mt-4 space-y-2 text-sm">
                      {category.options.map((option) => (
                        <li key={option} className="flex items-start gap-2">
                          <Check
                            className="text-accent-text mt-0.5 size-4 shrink-0"
                            aria-hidden="true"
                          />
                          {option}
                        </li>
                      ))}
                    </ul>
                  )}
                </Card>
              </Reveal>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  );
}
