// resources/js/components/home/FeaturedProjectsSection.tsx
import { Link } from "@inertiajs/react";
import { ArrowRight } from "lucide-react";
import { Reveal } from "@/components/common/Reveal";
import { SectionHeading } from "@/components/common/SectionHeading";
import { ContentCard } from "@/components/content/ContentCard";
import { Container } from "@/components/layout/Container";
import { Button } from "@/components/ui/button";
import { useT } from "@/hooks/use-t";
import type { Project } from "@/types";

interface FeaturedProjectsSectionProps {
  projects: Project[];
  projectsUrl: string;
}

export function FeaturedProjectsSection({
  projects,
  projectsUrl,
}: FeaturedProjectsSectionProps) {
  const t = useT();

  if (projects.length === 0) {
    return null;
  }

  return (
    <section className="bg-surface py-16 sm:py-24">
      <Container>
        <Reveal>
          <SectionHeading
            title={t("home.featuredProjects.title")}
            action={
              <Button
                asChild
                variant="outline"
                className="self-start sm:self-auto"
              >
                <Link href={projectsUrl}>
                  {t("home.featuredProjects.viewAll")}
                  <ArrowRight aria-hidden="true" />
                </Link>
              </Button>
            }
          />
        </Reveal>

        <ul className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {projects.map((project, index) => (
            <li key={project.id}>
              <Reveal delay={index * 75} className="h-full">
                <ContentCard project={project} />
              </Reveal>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  );
}

// resources/js/components/home/FeaturedProjectsSection.vue
<script setup lang="ts">
import { Link } from "@inertiajs/vue3";
import { useI18n } from "vue-i18n";
import Reveal from "@/components/common/Reveal.vue";
import ContentCard from "@/components/content/ContentCard.vue";
import { Button } from "@/components/ui/button";
import type { Project } from "@/types";

defineProps<{ projects: Project[]; projectsUrl: string }>();

const { t } = useI18n();
</script>

<template>
    <section v-if="projects.length" class="bg-secondary/30 py-20">
        <div class="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <Reveal class="flex flex-col items-start gap-4 sm:flex-row sm:items-end sm:justify-between">
                <h2 class="font-heading text-3xl font-semibold tracking-tight sm:text-4xl">
                    {{ t("home.featuredProjects.title") }}
                </h2>
                <Button as-child variant="outline">
                    <Link :href="projectsUrl">{{ t("home.featuredProjects.viewAll") }}</Link>
                </Button>
            </Reveal>

            <div class="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
                <Reveal v-for="(project, index) in projects" :key="project.id" :delay="index * 75">
                    <ContentCard :project="project" />
                </Reveal>
            </div>
        </div>
    </section>
</template>
