// resources/js/components/home/HeroSection.vue
<script setup lang="ts">
import { Link } from "@inertiajs/vue3";
import { useI18n } from "vue-i18n";
import { Button } from "@/components/ui/button";

defineProps<{
    title: string;
    subtitle: string;
    contactUrl: string;
    projectsUrl: string;
}>();

const { t } = useI18n();
</script>

<template>
    <section class="relative overflow-hidden">
        <div
            class="bg-gradient-warm pointer-events-none absolute inset-0"
            aria-hidden="true"
        />
        <div
            class="bg-primary/20 pointer-events-none absolute -top-24 -right-24 size-72 rounded-full blur-3xl"
            aria-hidden="true"
        />
        <div
            class="bg-primary/10 pointer-events-none absolute -bottom-32 left-1/4 size-96 rounded-full blur-3xl"
            aria-hidden="true"
        />

        <div
            class="animate-in fade-in slide-in-from-bottom-4 relative mx-auto flex max-w-6xl flex-col items-start gap-6 px-4 py-28 duration-700 sm:px-6 lg:px-8 lg:py-36"
        >
            <h1 class="font-heading max-w-3xl text-4xl font-semibold tracking-tight text-balance sm:text-5xl lg:text-6xl">
                {{ title }}
            </h1>
            <p class="text-muted-foreground max-w-xl text-lg text-pretty">
                {{ subtitle }}
            </p>
            <div class="flex flex-wrap gap-3 pt-2">
                <Button as-child size="lg" class="hover:shadow-warm-md transition-all duration-200 hover:scale-[1.02]">
                    <Link :href="contactUrl">{{ t("home.hero.cta") }}</Link>
                </Button>
                <Button
                    as-child
                    size="lg"
                    variant="outline"
                    class="hover:shadow-warm-sm transition-all duration-200 hover:scale-[1.02]"
                >
                    <Link :href="projectsUrl">{{ t("home.hero.secondaryCta") }}</Link>
                </Button>
            </div>
        </div>
    </section>
</template>

// resources/js/components/home/HeroSection.tsx
import { Link } from "@inertiajs/react";
import { Zap } from "lucide-react";
import { Container } from "@/components/layout/Container";
import { Button } from "@/components/ui/button";
import { useT } from "@/hooks/use-t";

interface HeroSectionProps {
  title: string;
  subtitle: string;
  contactUrl: string;
  projectsUrl: string;
}

export function HeroSection({
  title,
  subtitle,
  contactUrl,
  projectsUrl,
}: HeroSectionProps) {
  const t = useT();

  return (
    <section className="surface-navy bg-navy text-navy-foreground relative overflow-hidden">
      <div
        className="bg-blueprint absolute inset-0 mask-[radial-gradient(ellipse_at_top_right,black,transparent_70%)]"
        aria-hidden="true"
      />
      <div
        className="bg-accent/20 pointer-events-none absolute -top-32 -right-32 size-112 rounded-full blur-3xl"
        aria-hidden="true"
      />
      <Zap
        className="text-accent/10 pointer-events-none absolute top-1/2 right-[6%] hidden size-104 -translate-y-1/2 lg:block"
        strokeWidth={0.6}
        aria-hidden="true"
      />

      <Container className="animate-in fade-in slide-in-from-bottom-4 relative py-20 duration-700 sm:py-28 lg:py-36">
        <span
          className="bg-accent mb-6 block h-1 w-14 rounded-full"
          aria-hidden="true"
        />
        <h1 className="max-w-3xl text-4xl text-white sm:text-5xl lg:text-6xl">
          {title}
        </h1>
        <p className="text-navy-muted mt-6 max-w-xl text-lg text-pretty sm:text-xl">
          {subtitle}
        </p>
        <div className="mt-10 flex flex-wrap gap-3">
          <Button asChild variant="accent" size="lg">
            <Link href={contactUrl}>{t("home.hero.cta")}</Link>
          </Button>
          <Button asChild variant="inverse" size="lg">
            <Link href={projectsUrl}>{t("home.hero.secondaryCta")}</Link>
          </Button>
        </div>
      </Container>
    </section>
  );
}
