// resources/js/components/home/IntroSection.tsx
import { Reveal } from "@/components/common/Reveal";
import { SectionHeading } from "@/components/common/SectionHeading";
import { Container } from "@/components/layout/Container";

export function IntroSection({
  title,
  content,
}: {
  title: string;
  content: string;
}) {
  return (
    <section className="py-16 sm:py-24">
      <Container>
        <Reveal className="grid gap-8 lg:grid-cols-2 lg:gap-16">
          <SectionHeading title={title} />
          <p className="text-muted-foreground text-lg text-pretty lg:pt-6">
            {content}
          </p>
        </Reveal>
      </Container>
    </section>
  );
}

// resources/js/components/home/IntroSection.vue
<script setup lang="ts">
import Reveal from "@/components/common/Reveal.vue";

defineProps<{ title: string; content: string }>();
</script>

<template>
    <section class="mx-auto max-w-3xl px-4 py-20 text-center sm:px-6 lg:px-8">
        <Reveal>
            <h2 class="font-heading text-3xl font-semibold tracking-tight sm:text-4xl">
                {{ title }}
            </h2>
            <p class="text-muted-foreground mt-6 text-lg text-pretty">
                {{ content }}
            </p>
        </Reveal>
    </section>
</template>
