// resources/js/Pages/Projects/Show.vue
<script setup lang="ts">
import { Link } from "@inertiajs/vue3";
import { ArrowLeft, Calendar, MapPin, User } from "@lucide/vue";
import { ref } from "vue";
import { useI18n } from "vue-i18n";
import Reveal from "@/components/common/Reveal.vue";
import BlockRenderer from "@/components/content/BlockRenderer.vue";
import Breadcrumbs from "@/components/content/Breadcrumbs.vue";
import Lightbox from "@/components/content/Lightbox.vue";
import Seo from "@/components/seo/Seo.vue";
import { Badge } from "@/components/ui/badge";
import AppLayout from "@/layouts/AppLayout.vue";
import type { Breadcrumb, Project, SeoData } from "@/types";

const props = defineProps<{
    project: Project;
    breadcrumbs: Breadcrumb[];
    seo: SeoData;
}>();

const { t } = useI18n();

const lightboxIndex = ref<number | null>(null);
const galleryImages = props.project.gallery.map((image) => image.large);
</script>

<template>
    <Seo :seo="seo" />

    <AppLayout>
        <Breadcrumbs :items="breadcrumbs" />

        <article class="mx-auto max-w-3xl px-4 pb-24 sm:px-6 lg:px-8">
            <Reveal>
                <header class="mb-8 space-y-4">
                    <Badge variant="secondary">{{ project.category.name }}</Badge>
                    <h1 class="font-heading text-3xl font-semibold tracking-tight sm:text-4xl">
                        {{ project.title }}
                    </h1>

                    <dl class="text-muted-foreground grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">
                        <div v-if="project.location">
                            <dt class="flex items-center gap-1.5 font-medium">
                                <MapPin class="size-3.5" />
                                {{ t("content.location") }}
                            </dt>
                            <dd>{{ project.location }}</dd>
                        </div>
                        <div v-if="project.clientName">
                            <dt class="flex items-center gap-1.5 font-medium">
                                <User class="size-3.5" />
                                {{ t("content.client") }}
                            </dt>
                            <dd>{{ project.clientName }}</dd>
                        </div>
                        <div v-if="project.completedAt">
                            <dt class="flex items-center gap-1.5 font-medium">
                                <Calendar class="size-3.5" />
                                {{ t("content.completed") }}
                            </dt>
                            <dd>{{ project.completedAt }}</dd>
                        </div>
                    </dl>

                    <div v-if="project.tags.length" class="flex flex-wrap gap-2">
                        <Badge v-for="tag in project.tags" :key="tag.id" variant="outline">
                            {{ tag.name }}
                        </Badge>
                    </div>
                </header>
            </Reveal>

            <img
                v-if="project.featuredImageUrl"
                :src="project.featuredImageUrl"
                :alt="project.title"
                class="shadow-warm-md mb-10 w-full rounded-xl"
            />

            <BlockRenderer v-if="project.blocks" :blocks="project.blocks" />

            <div v-if="project.gallery.length" class="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3">
                <button
                    v-for="(image, index) in project.gallery"
                    :key="index"
                    type="button"
                    class="focus-visible:ring-ring block overflow-hidden rounded-lg focus-visible:ring-2 focus-visible:outline-none"
                    @click="lightboxIndex = index"
                >
                    <img
                        :src="image.thumbnail"
                        loading="lazy"
                        class="aspect-square w-full rounded-lg object-cover transition-transform duration-300 hover:scale-105"
                        :alt="`${project.title} ${index + 1}`"
                    />
                </button>
            </div>

            <Lightbox v-model:index="lightboxIndex" :images="galleryImages" />

            <div v-if="breadcrumbs[1]?.url" class="mt-12 border-t pt-6">
                <Link
                    :href="breadcrumbs[1].url"
                    class="text-muted-foreground hover:text-foreground group flex items-center gap-1.5 text-sm transition-colors"
                >
                    <ArrowLeft class="size-4 transition-transform duration-200 group-hover:-translate-x-1" />
                    {{ t("content.backToProjects") }}
                </Link>
            </div>
        </article>
    </AppLayout>
</template>

// resources/js/Pages/Projects/Show.tsx
import { Link, usePage } from "@inertiajs/react";
import { ArrowLeft, Calendar, MapPin, User } from "lucide-react";
import { BlockRenderer } from "@/components/content/BlockRenderer";
import { Gallery } from "@/components/content/Gallery";
import { Container } from "@/components/layout/Container";
import { PageHeader } from "@/components/layout/PageHeader";
import { Badge } from "@/components/ui/badge";
import { useT } from "@/hooks/use-t";
import { formatDate } from "@/lib/utils";
import type { Breadcrumb, Project } from "@/types";

interface ShowProps {
  project: Project;
  breadcrumbs: Breadcrumb[];
}

export default function Show({ project, breadcrumbs }: ShowProps) {
  const t = useT();
  const { locale } = usePage().props;
  const backUrl = breadcrumbs[1]?.url;

  const details = [
    { icon: MapPin, label: t("content.location"), value: project.location },
    { icon: User, label: t("content.client"), value: project.clientName },
    {
      icon: Calendar,
      label: t("content.completed"),
      value: project.completedAt
        ? formatDate(project.completedAt, locale.current)
        : null,
    },
  ].filter((detail) => detail.value);

  return (
    <>
      <PageHeader breadcrumbs={breadcrumbs} title={project.title}>
        <div className="mt-6 space-y-5">
          <Badge variant="accent">{project.category.name}</Badge>

          {details.length > 0 && (
            <dl className="text-muted-foreground grid grid-cols-1 gap-4 text-sm sm:grid-cols-3">
              {details.map(({ icon: Icon, label, value }) => (
                <div key={label}>
                  <dt className="text-foreground flex items-center gap-1.5 font-semibold">
                    <Icon
                      className="text-accent-text size-4"
                      aria-hidden="true"
                    />
                    {label}
                  </dt>
                  <dd className="mt-0.5">{value}</dd>
                </div>
              ))}
            </dl>
          )}

          {project.tags.length > 0 && (
            <ul className="flex flex-wrap gap-2">
              {project.tags.map((tag) => (
                <li key={tag.id}>
                  <Badge variant="outline">{tag.name}</Badge>
                </li>
              ))}
            </ul>
          )}
        </div>
      </PageHeader>

      <Container size="narrow" className="py-12 lg:py-16">
        {project.featuredImageUrl && (
          <img
            src={project.featuredImageUrl}
            alt=""
            className="shadow-card mb-10 w-full rounded-lg"
          />
        )}

        {project.blocks && <BlockRenderer blocks={project.blocks} />}

        {project.gallery.length > 0 && (
          <div className="mt-10">
            <Gallery
              items={project.gallery.map((image, index) => ({
                thumbnail: image.thumbnail,
                full: image.large,
                alt: `${project.title} ${index + 1}`,
              }))}
            />
          </div>
        )}

        {backUrl && (
          <div className="mt-12 border-t pt-6">
            <Link
              href={backUrl}
              className="text-primary group inline-flex items-center gap-2 text-sm font-semibold hover:underline underline-offset-4"
            >
              <ArrowLeft
                className="size-4 transition-transform duration-200 group-hover:-translate-x-1"
                aria-hidden="true"
              />
              {t("content.backToProjects")}
            </Link>
          </div>
        )}
      </Container>
    </>
  );
}
